### ISSUE TITLE
Cannot remove taxonomy terms from filtered archive

### ISSUE THREAD

**Issue by marpa** [clas-web/multi-taxonomy-browser#10]
Taxonomy terms cannot be removed from a mt-filtered-archive query, see:
https://clasconnections.uncc.edu/?mt-filtered-archive&post-type=connection&connection-link=american-culture,composition&connection-group=

**Comment by atrus1701** [comment]
32d6d8aa1ae2c198e3e508fd1bec0885c1f9a678
