### ISSUE TITLE
Widget filter not finding posts that have selected terms

### ISSUE THREAD

**Issue by marpa** [clas-web/multi-taxonomy-browser#5]
The widget filter is not always finding posts that have selected terms, compare:
* https://clas-incubator-wp.uncc.edu/techne/?mt-filtered-archive&post-type=post&category=math,multimedia&post_tag=
* https://clas-incubator-wp.uncc.edu/techne/?mt-filtered-archive&post-type=post&category=math,programming

**Comment by marpa** [comment]
Within categories related to math, the following work:
productivity, programming, visualization
The following math-related categories do NOT work:
analysis, multimedia

The difference is the "Analysis" and "Multimedia" have sub-categories.  Have confirmed that any category that has a sub-category will not work as a "related category."

**Comment by cbarto11** [comment]
cf6307e4dea964c24543f661534ec17d36d286a3

The problem has to do with "multimedia" being a parent of several other different terms in category.  I added the option to ignore children in the "tax_query" array.
