### ISSUE TITLE
Add term filter, sort and max number

### ISSUE THREAD

**Issue by marpa** [clas-web/multi-taxonomy-browser#8]
Add the following options:

1. Filter
This would limit the terms displayed to those that include the filter term on posts they have been applied to
2. Sort
This would have options for sorting by name and count and would have checkbox for reverse order
3. Max Terms
This would allow users to specify the maximum number of terms to display

If a filter term is specified then the output css should included "filtered" in the css (maybe...)

**Comment by atrus1701** [comment]
70165d7f47c19ab407e7ecd058ecd4ac3d505b0b
