### ISSUE TITLE
Search with multiple taxonomies terms not working 

### ISSUE THREAD

**Issue by marpa** [clas-web/multi-taxonomy-browser#9]
Search with multiple taxonomies terms not working on UNC Charlotte Faculty Connections site, see:
https://pages.uncc.edu/connections/?mt-filtered-archive&post-type=connection&connection-link=adaptation,culture&connection-group=

Same search does work on CLAS Connections site, see:
https://clasconnections.uncc.edu/?mt-filtered-archive&post-type=connection&connection-link=adaptation,culture&connection-group=

Confirmed that both sites are using the same version of the Multi-taxonomy browser plugin

**Comment by atrus1701** [comment]
This was actually an old "mt-archive.php" file found in the "variations-template-theme" folder on the pages server.
